<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
    public function getPathAttribute()
    {
        return asset('api/question/'.$this->slug);
    }

    protected $fillable = [
        'title', 'slug', 'category_id','user_id','body'
    ];

//    protected $guarded = [];

    function user()
    {
        return $this->belongsTo(User::class);
    }
    function replies()
    {
        return $this->hasMany(Reply::class);
    }
    function category()
    {
        return $this->belongsTo(Category::class);
    }
}
